# permissions for end users to edit items.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: item-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resolvulator
    app.kubernetes.io/part-of: resolvulator
    app.kubernetes.io/managed-by: kustomize
  name: item-editor-role
rules:
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - items
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - items/status
  verbs:
  - get
