---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - installedthings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - installedthings/finalizers
  verbs:
  - update
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - installedthings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - things
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - things/finalizers
  verbs:
  - update
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - things/status
  verbs:
  - get
  - patch
  - update
