# permissions for end users to view things.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: thing-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resolvulator
    app.kubernetes.io/part-of: resolvulator
    app.kubernetes.io/managed-by: kustomize
  name: thing-viewer-role
rules:
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - things
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resolvulator.resolvulator.io
  resources:
  - things/status
  verbs:
  - get
